# Generated by Django 4.2.16 on 2024-11-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id_card_back',
            field=models.ImageField(max_length=1000, upload_to='id_cards/back/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id_card_front',
            field=models.ImageField(max_length=1000, upload_to='id_cards/front/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(max_length=1000, upload_to='profiles/'),
        ),
    ]
