# Generated by Django 4.2.16 on 2024-12-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_transaction_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
