# Generated by Django 4.2.16 on 2024-12-03 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_transaction_cancel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_tr', to='app.vehicle'),
        ),
    ]
